### PR TITLE
Implement Divmod runtime platforms for modern versions of Internet Explorer

### LINKED ISSUE #16: IE11triggers Netscape runtime selection due to false UA string
IE11 identifies itself as  

'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko'

which leads subsequently to the wrong assumption of the DivMod UA detection code, that the browser runtime should be set to Firefox with XPath capabilities being present. The error manifests itself by IE11 stating, that XPathResult is undefined.

A possible fix is expanding  the test for IE to test for 'Netscape'  and no XPathNamespace defined, while the actual 'Netscape' type browser Firefox would then have XPathNamespace defined.

For an explanation of the UA strings used by IE11, please see:
http://blogs.msdn.com/b/ieinternals/archive/2013/09/21/internet-explorer-11-user-agent-string-ua-string-sniffing-compatibility-with-gecko-webkit.aspx

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-11-11T05:12:15Z
 * owner: werner-thieprojects
 * the launchpad url was https://bugs.launchpad.net/bugs/1249946

### PR DESCRIPTION
**Pull request by jonathanj**
Fixes #16.

Introduce new runtime platforms for all versions of Internet Explorer:

 * Legacy: 6 and 7
 * Semi-modern: 8 and 9
 * Modern: 10+

The `XPathSupportingPlatform` hack platform has also been removed in favour of the native APIs which are much faster and support modern HTML features now.

This PR also fixes the issue where some platform runtime methods with the same name as official browser APIs are leaked into the global object in some versions of IE and break feature detection (as well as having the wrong signature.)

[Review on Reviewable](https://reviewable.io/reviews/twisted/nevow/56)

### CODE REVIEW

**Comment by mithrandi** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[nevow/js/Divmod/Runtime/__init__.js, line 77 \[r3\]](https://reviewable.io:443/reviews/twisted/nevow/56#-K1GAvkOMXHr_r503zRQ)** ([raw file](https://github.com/twisted/nevow/blob/508d60c1474c17f9d74ccc282dbcf9b456432ce8/nevow/js/Divmod/Runtime/__init__.js#L77)):</sup>
The function actually gets an *element*, not a document.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/nevow/56)

**Comment by mithrandi** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/nevow/56)

**Comment by jonathanj** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[nevow/js/Divmod/Runtime/__init__.js, line 77 \[r3\]](https://reviewable.io:443/reviews/twisted/nevow/56#-K1GAvkOMXHr_r503zRQ)** ([raw file](https://github.com/twisted/nevow/blob/508d60c1474c17f9d74ccc282dbcf9b456432ce8/nevow/js/Divmod/Runtime/__init__.js#L77)):</sup>
Yes, quite right. I fixed the docstring.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/nevow/56)

**Comment by mithrandi** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/twisted/nevow/56)

**Pull request merged**
